---
- name: Mise en place du script d'audit Linux
  hosts: Cibles
  vars:
    log_file_path: "/var/log/system_audit.log"
    slack_webhook_url: "https://hooks.slack.com/services/xxx/xxx/xxx"

  tasks:
    - name: Copier le script d'audit
      copy:
        src: audit.sh
        dest: /tmp/audit.sh
        mode: '0755'

    - name: Exécuter le script d'audit
      command: bash /tmp/audit.sh
      register: audit_result
      ignore_errors: yes

    - name: Vérification de l'éxécution 
      fail:
        msg: "L'exécution du script d'audit a échoué."
      when: audit_result.failed

    - name: Vérification du fichier de log
      stat:
        path: "{{ log_file_path }}"
      register: log_stats

    - name: Modifier les permissions du fichier de log si nécessaire
      file:
        path: "{{ log_file_path }}"
        mode: '0644'
      when: log_stats.stat.exists == True

    - name: Lire les derniers logs
      command: tail -n 10 {{ log_file_path }}
      register: last_logs
      when: log_stats.stat.exists == True

    - name: Notification Slack en cas d'erreur
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body:
          msg: "Un problème a été détecté dans l'audit : {{ last_logs.stdout }}"
        body_format: json
      when: "'ERROR' in last_logs.stdout"

    - name: Notification de fin d'audit
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body:
          msg: "L'audit a été terminé avec succès. Voici les résultats : {{ audit_result.stdout }}"
        body_format: json
